modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All rights reserved"
[[mods]]
modId="morewoolmod"
version="1.0.0"
displayName="More Wool Mod"
authors="Rin-Chan"
description='''
Making sheeps grow and drop more wool.
'''
[[dependencies.morewoolmod]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.morewoolmod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
