modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
[[mods]]
modId="morewoolmod"
version="1.0.1"
displayName="More Wool Mod"
logoFile="examplemod.png"
credits="Developer: Rin-Chan"
authors="Rin-Chan"
description='''
Making sheeps grow and drop more wool.
'''

[[dependencies.morewoolmod]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morewoolmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
